# Generated by Django 4.1.7 on 2023-03-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dchatapp', '0003_chatmessages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatMessages',
            new_name='ChatMessage',
        ),
    ]
