# Generated by Django 4.1.7 on 2023-03-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dchatapp', '0004_rename_chatmessages_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='my_friends', to='dchatapp.chatmessage'),
        ),
    ]
