# Generated by Django 4.1.7 on 2023-03-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dchatapp', '0005_alter_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='my_friends', to='dchatapp.friend'),
        ),
    ]
