# Generated by Django 4.1.7 on 2023-03-25 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dchatapp', '0006_alter_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
