# Generated by Django 4.1.7 on 2023-03-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dchatapp', '0008_alter_chatmessage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='date',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
