# Generated by Django 4.1.7 on 2023-03-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dchatapp', '0009_alter_chatmessage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
